name: gg_console_colors
description: A Dart package providing a collection of console colors to easily colorize command line outputs.
version: 1.0.0
repository: https://github.com/inlavigo/gg_console_colors.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  colorize: ^3.0.0
  gg_args: ^1.0.3
  gg_process: ^1.0.5
  path: ^1.8.0

dev_dependencies:
  gg_capture_print: ^1.0.2
  gg_check: ^1.0.2
  lints: ^3.0.0
  pana: ^0.22.2
  test: ^1.24.0
