name: gg_console_colors
description: A Dart package providing a collection of console colors to easily colorize command line outputs.
version: 2.1.5
repository: https://github.com/inlavigo/gg_console_colors.git

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0